dist: xenial
language: python
python: 3.7.6

sudo: false

# The apt packages below are needed for sphinx builds
addons:
  apt:
    packages:
      - texlive-latex-extra
      - dvipng
      - graphviz
      - liblapack-dev

env:
  global:
    - CRDS_SERVER_URL="https://jwst-crds.stsci.edu"
    - CRDS_PATH="/tmp/crds_cache"
    - CRDS_CLIENT_RETRY_COUNT=3
    - CRDS_CLIENT_RETRY_DELAY_SECONDS=20
    - TEST_COMMAND="pytest"
    - PIP_DEPENDENCIES=".[test]"

matrix:
  include:
    - python: 3.6.9
    - python: 3.7.6
    - python: 3.8.1

install:
  - pip install $PIP_DEPENDENCIES
  - pip install git+https://github.com/eslavich/asdf.git

script:
  - $TEST_COMMAND
